apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    kwok.x-k8s.io/node: fake
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: kwok-node-1
    kubernetes.io/os: linux
    kubernetes.io/role: agent
    node-role.kubernetes.io/agent: ""
    type: kwok
  name: kwok-node-1
spec:
  taints: # Avoid scheduling actual running pods to fake Node
    - effect: NoExecute
      key: kwok.x-k8s.io/node
      value: fake
status:
  allocatable:
    cpu: 4
    memory: 4Gi
    pods: "55"
  capacity:
    cpu: "4"
    memory: 4Gi
    pods: "55"
  nodeInfo:
    architecture: arm64
    kubeProxyVersion: fake
    kubeletVersion: fake
    operatingSystem: linux
