apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: git
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/network-charles/kwok-gitops.git
  ref:
    branch: main
  secretRef:
    name: github-auth
