apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: others
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: git
    namespace: flux-system
  path: "/gitops/kustomization/others/overlays/modify-number-of-pods"
  prune: true
  timeout: 1m
